export const site = {
  name: "Vendere Gioielli Torino",
  brandName: "Vendere Gioielli Torino",
  legalName: "Vendere Gioielli Torino — Maison Obagem",
  domain: "vendere-gioielli-torino.site",
  url: "https://vendere-gioielli-torino.site",
  city: "Torino",
  citySlug: "torino",
  postalCode: "10121",
  department: "Città Metropolitana di Torino",
  region: "Piemonte",
  regionContext: "Torino (10121 / 10123 / 10128 / 10131 / 10138 / 10024 / 10098) — Centro Storico, Via Roma, Piazza San Carlo, Crocetta, Collina Torinese, Cit Turin, San Salvario, Moncalieri, Rivoli e Langhe-Roero",
  tagline: "Gabinetto Gemmologico & Acquisto Diretto di Alta Gioielleria a Torino",
  description: "Vendere Gioielli Torino: perizia gemmologica indipendente e acquisto diretto di diamanti certificati (GIA, HRD, IGI) secondo listino ufficiale Rapaport, alta gioielleria d'epoca e firmata (Bulgari, Cartier, Buccellati, Van Cleef & Arpels, Damiani), oro 18 carati e orologi di prestigio (Rolex, Patek Philippe, Audemars Piguet). Salotti riservati in Via Roma e perizie a domicilio a Torino, Crocetta, Collina, Moncalieri e in tutto il Piemonte. Bonifico bancario istantaneo in EUR.",
  port: 3800,

  phone: "+33 1 48 87 81 44",
  phoneDisplay: "+33 1 48 87 81 44",
  phoneIntl: "+33148878144",
  whatsappPhone: "+33148878144",
  email: "contatto@vendere-gioielli-torino.site",
  whatsappUrl: "https://wa.me/33148872337",

  address: {
    street: "Via Roma 28",
    postalCode: "10121",
    city: "Torino",
    region: "Piemonte",
    country: "IT",
    geo: { lat: 45.0677, lng: 7.6824 },
  },

  openingHours: [
    { day: "Lunedì - Venerdì", hours: "09:30 - 18:30" },
    { day: "Sabato", hours: "10:00 - 17:30 (su appuntamento)" },
    { day: "Domenica", hours: "Chiuso" },
  ],

  stats: [
    { value: "40+", label: "Anni di Tradizione" },
    { value: "100%", label: "Bonifico Istantaneo in EUR" },
    { value: "GIA / HRD", label: "Gemmologi Diplomati" },
    { value: "Rapaport", label: "Listino Internazionale Ufficiale" },
  ],

  areasServed: [
    "Torino",
    "Centro Storico",
    "Via Roma",
    "Piazza San Carlo",
    "Piazza Castello",
    "Via Lagrange",
    "Via Carlo Alberto",
    "Crocetta",
    "Collina Torinese",
    "Borgo Po",
    "Gran Madre",
    "Crimea",
    "Cit Turin",
    "San Donato",
    "San Salvario",
    "Parco del Valentino",
    "Moncalieri",
    "Chieri",
    "Rivoli",
    "Langhe e Roero",
    "Alba",
    "Piemonte",
  ],
};
